<?php $title='Teacher profile'; $row=fn($l,$v)=>'<div class="kv"><span>'.$l.'</span><b>'.($v!==null&&$v!==''?e($v):'—').'</b></div>'; ?>
<div class="row between noprint"><a href="<?=url('ledger/index')?>">← Back to ledger</a><div class="row"><button class="btn" data-print>Print</button><?php if(Auth::can('teachers.manage')): ?><a class="btn primary" href="<?=url('teachers/form',['id'=>$t['id']])?>">Edit</a><?php endif; ?></div></div>
<section class="card hero-p"><?=avatar($t,'big')?><div><h1><?=e(fullname($t))?></h1><p class="muted"><?=e($t['designation'])?> · <?=e($t['school_name']?:'No school')?></p>
<div class="row"><span class="pill <?=$t['payroll_status']==='on_payroll'?'active':'disabled'?>"><?=$t['payroll_status']==='on_payroll'?'On payroll':'Off payroll'?></span><span class="pill"><?=ucfirst($t['termination_status'])?></span>
<span class="pill <?=$t['verified']?'active':''?>"><?=$t['verified']?'Verified':'Not verified'?></span><span class="pill">Biometrics <?=$t['biometrics_status']?></span></div></div></section>
<?php if($t['termination_status']==='active'): ?><div class="row noprint" style="margin-bottom:1rem">
<?php if(can_request('transfer')): ?><a class="btn" href="<?=url('movements/create',['type'=>'transfer','teacher_id'=>$t['id']])?>">Transfer</a><?php endif; ?>
<?php if(can_request('retirement')): ?><a class="btn" href="<?=url('movements/create',['type'=>'retirement','teacher_id'=>$t['id']])?>">Retire</a><?php endif; ?>
</div><?php endif; ?>
<?php if(Auth::can('biometrics.manage')): ?><div class="row noprint" style="margin-bottom:1rem"><a class="btn" href="<?=url('biometrics/capture',['id'=>$t['id']])?>">Capture biometrics</a><?php if($t['biometrics_status']==='captured'): ?><a class="btn" href="<?=url('biometrics/verify',['id'=>$t['id']])?>"><?=$t['verified']?'View verification':'Verify teacher'?></a><?php endif; ?></div><?php endif; ?>
<?php if($t['verified']): ?><p class="muted">Verified by <?=e($t['verified_by_name']?:'an administrator')?> on <?=fdate($t['verified_at'])?>.</p><?php endif; ?>
<div class="cols"><section class="card"><h2>Personal and employment</h2><div class="kvs">
<?=$row('Registration number',$t['registration_no'])?><?=$row('File number',$t['file_no'])?><?=$row('Date of birth',fdate($t['date_of_birth']))?><?=$row('Contact',$t['contact'])?><?=$row('Email',$t['email'])?>
<?=$row('Date employed',fdate($t['date_employed']))?><?=$row('Date file opened',fdate($t['date_opened']))?><?=$row('Department',$t['department'])?><?=$row('Salary scale',$t['salary_scale'])?>
<?=$row('Retirement',$t['retirement_year'].' (age '.$t['retirement_age'].')')?><?=$row('Health status',$t['health_status'])?></div></section>
<section class="card"><h2>Identification</h2><div class="kvs"><?=$row('NIN',$t['nin'])?><?=$row('IPPS number',$t['ipps_no'])?><?=$row('NSSF number',$t['nssf_no'])?><?=$row('TIN',$t['tin'])?></div>
<h2 style="margin-top:1.25rem">Teaching</h2><div class="kvs"><?=$row('Subjects',$t['subjects'])?><?=$row('Classes',$t['classes'])?></div></section></div>
<div class="cols"><section class="card"><h2>School history</h2><ul class="feed"><?php foreach($posts as $i=>$p): ?><li><span class="dot <?=$i===0&&!$p['to_date']?'login':''?>"></span><div><b><?=e($p['school_name'])?></b> <?=$i===0&&!$p['to_date']?'<span class="pill active">Current</span>':''?><small><?=fdate($p['from_date'])?> to <?=$p['to_date']?fdate($p['to_date']):'present'?> · <?=e($p['designation'])?><?=!$p['to_date']?' · '.e(tenure($p['from_date'])):''?></small></div></li><?php endforeach; if(!$posts): ?><li class="empty">No postings recorded.</li><?php endif; ?></ul></section>
<section class="card"><h2>Next of kin</h2><ul class="feed"><?php foreach($kin as $k): ?><li><div><b><?=e($k['name'])?></b> <?=$k['relationship']?'('.e($k['relationship']).')':''?><small><?=e($k['contact'])?><?=$k['nin']?' · NIN '.e($k['nin']):''?></small></div></li><?php endforeach; ?></ul></section></div>
<section class="card"><h2>Movements and approvals</h2><ul class="feed"><?php foreach($moves as $m): ?><li><span class="dot <?=$m['status']==='approved'?'login':($m['status']==='rejected'?'login_failed':'')?>"></span><div><b><?=e(MOVE_TYPES[$m['type']])?></b> <?=move_pill($m['status'])?><small><?=fdate($m['effective_date'])?><?php if($m['type']==='transfer'): ?> · <?=e($m['from_name'])?> → <?=e($m['to_name'])?><?php endif; ?><?=$m['reason']?' · '.e($m['reason']):''?></small></div></li><?php endforeach; if(!$moves): ?><li class="empty">No requests yet.</li><?php endif; ?></ul></section>
