<?php $title='Capture biometrics'; $S=BiometricsController::SLOTS; $img=fn($id)=>url('biometrics/image',['id'=>$id]); $fp=count(array_diff_key($samples,['face'=>1])); ?>
<div class="row between"><a href="<?=url('biometrics/index')?>">← Back</a><?php if($t['biometrics_status']==='captured'): ?><a class="btn primary" href="<?=url('biometrics/verify',['id'=>$t['id']])?>">Go to verification</a><?php endif; ?></div>
<h1><?=e(fullname($t))?></h1><p class="muted"><?=e($t['registration_no'])?> · <?=e($t['school_name'])?></p>
<div id="bio" data-teacher="<?=$t['id']?>" data-csrf="<?=e(Csrf::token())?>" data-save="<?=url('biometrics/save')?>" data-remove="<?=url('biometrics/remove')?>" data-image="<?=url('biometrics/image')?>&id=" data-min="<?=BiometricsController::MIN_FP?>">
<section class="card"><?php if($t['biometric_consent_at']): ?><p class="ok">Consent recorded on <?=fdate($t['biometric_consent_at'])?>.</p><input type="checkbox" id="consent" checked hidden>
<?php else: ?><label class="check"><input type="checkbox" id="consent"> The teacher has been told why their fingerprints and photo are collected and has agreed.</label><?php endif; ?>
<p class="muted" id="summary">Fingerprints: <b id="nfp"><?=$fp?></b> of 10 (at least <?=BiometricsController::MIN_FP?> needed) · Face: <b id="nface"><?=isset($samples['face'])?'captured':'missing'?></b></p><div id="msg" class="alert" hidden></div></section>
<section class="card"><h2>Face</h2><div class="faceblk"><div><video id="cam" autoplay playsinline muted hidden></video><img id="faceimg" class="facepic" alt="" <?=isset($samples['face'])?'src="'.$img($samples['face']['id']).'"':'hidden'?>></div>
<div class="row"><button type="button" class="btn" id="camstart">Start camera</button><button type="button" class="btn primary" id="snap" hidden>Take photo</button><label class="btn">Upload photo<input type="file" id="facefile" accept="image/jpeg,image/png" hidden></label></div></div></section>
<section class="card"><h2>Fingerprints</h2><p class="muted" id="scannernote">No scanner connected. Upload a fingerprint image for each finger. The desktop app (Phase 8) adds direct scanner capture.</p>
<div class="fingers"><?php foreach($S as $k=>$l): $has=isset($samples[$k]); ?><div class="finger <?=$has?'done':''?>" data-slot="<?=$k?>"><b><?=e($l)?></b><img alt="" <?=$has?'src="'.$img($samples[$k]['id']).'"':'hidden'?>><small class="st"><?=$has?'Captured':'Empty'?></small>
<div class="row"><button type="button" class="btn scan" hidden>Scan</button><label class="btn">Upload<input type="file" accept="image/jpeg,image/png,image/bmp" hidden></label><button type="button" class="link del" <?=$has?'':'hidden'?>>Remove</button></div></div><?php endforeach; ?></div></section></div>
<script src="<?=asset('js/biometrics.js')?>"></script>
