<?php $title='Quarterly verification'; $S=BiometricsController::SLOTS; $img=fn($id)=>url('biometrics/quarterlyimage',['id'=>$id]); $ready=isset($samples['face'])&&$stats['fp']>=BiometricsController::MIN_FP; ?>
<div class="row between"><a href="<?=url('biometrics/quarterly')?>">← Back to quarterly checks</a><?php if(empty($cycle['verified_at'])): ?><a class="btn" href="<?=url('biometrics/quarterlycapture',['id'=>$t['id']])?>">Review captures</a><?php endif; ?></div>
<h1>Quarter <?=$period['quarter']?>, <?=$period['year']?>: <?=e(fullname($t))?><?=verified_tick($t)?></h1>
<?php if(!empty($cycle['verified_at'])): ?><div class="alert ok">Quarterly verification completed by <?=e($cycle['verified_by_name']?:'an administrator')?> on <?=fdate($cycle['verified_at'])?>.</div><?php endif; ?>
<div class="cols"><section class="card"><h2>Face comparison</h2><div class="row" style="align-items:flex-start;flex-wrap:nowrap"><figure class="cmp"><?=photo_url($t)?'<img class="facepic" src="'.photo_url($t).'" alt="">':'<span class="thumb big">'.e(initials($t)).'</span>'?><figcaption>Profile photo</figcaption></figure>
<figure class="cmp"><?php if(isset($samples['face'])): ?><img class="facepic" src="<?=$img($samples['face']['id'])?>" alt="Face captured for quarterly verification"><?php else: ?><span class="empty">No face image captured</span><?php endif; ?><figcaption>Captured this quarter</figcaption></figure></div></section>
<section class="card"><h2>Record to check against</h2><div class="kvs"><?php foreach(['Registration number'=>$t['registration_no'],'Date of birth'=>fdate($t['date_of_birth']),'NIN'=>$t['nin'],'IPPS number'=>$t['ipps_no'],'School'=>$t['school_name']] as $l=>$v): ?><div class="kv"><span><?=e($l)?></span><b><?=e($v?:'—')?></b></div><?php endforeach; ?></div></section></div>
<section class="card"><h2>Fingerprints (<?=$stats['fp']?>/10)</h2><div class="fingers"><?php foreach($S as $k=>$l): if(isset($samples[$k])): ?><div class="finger done"><b><?=e($l)?></b><img src="<?=$img($samples[$k]['id'])?>" alt=""><small><?=$samples[$k]['quality']!==null?'Quality '.(int)$samples[$k]['quality']:'Captured'?></small></div><?php endif; endforeach; ?></div></section>
<?php if(empty($cycle['verified_at'])&&!$ready): ?><div class="alert warn">Capture a new face image and at least <?=BiometricsController::MIN_FP?> fingerprints for this quarter before verification.</div>
<?php elseif(empty($cycle['verified_at'])): ?><section class="card narrow"><h2>Confirm quarterly check</h2><form method="post" action="<?=url('biometrics/quarterlyconfirm')?>" class="form"><?=Csrf::field()?><input type="hidden" name="id" value="<?=$t['id']?>">
<label class="check"><input type="checkbox" name="confirm" value="1" required> I checked this teacher in person against the records and the biometrics captured for this quarter.</label>
<label>Note (optional)<input name="note"></label><button class="btn primary">Complete quarterly verification</button></form></section><?php endif; ?>
