<?php $title='Quarterly teacher checks'; $names=['due'=>'Due','progress'=>'In progress','verified'=>'Verified']; ?>
<div class="row between"><div><h1>Quarterly biometric checks</h1><p class="muted">Quarter <?=$period['quarter']?>, <?=$period['year']?> · Each active teacher needs a new face image and at least <?=BiometricsController::MIN_FP?> fingerprints this quarter.</p></div><a class="btn" href="<?=url('biometrics/index')?>">Initial verification</a></div>
<div class="tabs" style="margin-bottom:1rem"><?php foreach($names as $k=>$n): ?><a class="tablink <?=$stage===$k?'on':''?>" href="<?=url('biometrics/quarterly',['stage'=>$k,'q'=>$q])?>"><?=e($n)?> (<?=$counts[$k]?>)</a><?php endforeach; ?></div>
<form class="filters" method="get"><input type="hidden" name="r" value="biometrics/quarterly"><input type="hidden" name="stage" value="<?=e($stage)?>"><input name="q" value="<?=e($q)?>" placeholder="Search name or registration number"><button class="btn">Search</button></form>
<div class="card tablewrap"><table><thead><tr><th>Teacher</th><th>School</th><th>Quarterly biometrics</th><th>Status</th><th></th></tr></thead><tbody>
<?php foreach($rows as $t): ?><tr><td data-l="Teacher"><div class="who"><?=avatar($t)?><div><a href="<?=url('ledger/profile',['id'=>$t['id']])?>"><b><?=e(fullname($t))?></b><?=verified_tick($t)?></a><small><?=e($t['registration_no'])?></small></div></div></td>
<td data-l="School"><?=e($t['school_name']?:'—')?></td><td data-l="Quarterly biometrics"><?=$t['fp']?>/10 fingerprints · <?=$t['face']?'Face captured':'Face needed'?></td>
<td data-l="Status"><?php if($t['verified_at']): ?><span class="pill active">Verified <?=fdate($t['verified_at'])?></span><?php elseif($t['consented_at']): ?><span class="pill warnp">In progress</span><?php else: ?><span class="pill">Due</span><?php endif; ?></td>
<td class="act"><?php if($t['verified_at']): ?><a href="<?=url('biometrics/quarterlyverify',['id'=>$t['id']])?>">View</a><?php else: ?><a href="<?=url('biometrics/quarterlycapture',['id'=>$t['id']])?>"><?=$t['consented_at']?'Continue':'Start check'?></a><?php endif; ?></td></tr>
<?php endforeach; if(!$rows): ?><tr><td colspan="5" class="empty">No teachers in this list.</td></tr><?php endif; ?></tbody></table></div><?=pager($page,$pages,'biometrics/quarterly',$f)?>
