<?php $title='Verify teacher'; $S=BiometricsController::SLOTS; $img=fn($id)=>url('biometrics/image',['id'=>$id]); $ready=$t['biometrics_status']==='captured'; ?>
<div class="row between"><a href="<?=url('biometrics/index')?>">← Back</a><a class="btn" href="<?=url('biometrics/capture',['id'=>$t['id']])?>">Re-capture biometrics</a></div>
<h1>Verify <?=e(fullname($t))?></h1><?php if($t['verified']): ?><div class="alert ok">Verified by <?=e($by?:'an administrator')?> on <?=fdate($t['verified_at'])?>.</div><?php endif; ?>
<div class="cols"><section class="card"><h2>Face comparison</h2><div class="row" style="align-items:flex-start;flex-wrap:nowrap"><figure class="cmp"><?=photo_url($t)?'<img class="facepic" src="'.photo_url($t).'" alt="">':'<span class="thumb big">'.e(initials($t)).'</span>'?><figcaption>Profile photo</figcaption></figure>
<figure class="cmp"><?=isset($samples['face'])?'<img class="facepic" src="'.$img($samples['face']['id']).'" alt="">':'<span class="empty">Not captured</span>'?><figcaption>Captured face</figcaption></figure></div></section>
<section class="card"><h2>Record to check against</h2><div class="kvs"><?php foreach(['Registration number'=>$t['registration_no'],'Date of birth'=>fdate($t['date_of_birth']),'NIN'=>$t['nin'],'IPPS number'=>$t['ipps_no'],'File number'=>$t['file_no'],'School'=>$t['school_name']] as $l=>$v): ?><div class="kv"><span><?=$l?></span><b><?=e($v?:'—')?></b></div><?php endforeach; ?></div></section></div>
<section class="card"><h2>Fingerprints (<?=count(array_diff_key($samples,['face'=>1]))?>/10)</h2><div class="fingers"><?php foreach($S as $k=>$l): if(isset($samples[$k])): ?><div class="finger done"><b><?=e($l)?></b><img src="<?=$img($samples[$k]['id'])?>" alt=""><small><?=$samples[$k]['quality']!==null?'Quality '.(int)$samples[$k]['quality']:'Captured'?></small></div><?php endif; endforeach; ?></div></section>
<?php if(!$ready): ?><div class="alert warn">Biometrics are incomplete. A face photo and at least <?=BiometricsController::MIN_FP?> fingerprints are needed before verification.</div>
<?php elseif(!$t['verified']): ?><section class="card narrow"><h2>Confirm identity</h2><form method="post" action="<?=url('biometrics/confirm')?>" class="form"><?=Csrf::field()?><input type="hidden" name="id" value="<?=$t['id']?>">
<label class="check"><input type="checkbox" name="confirm" value="1" required> I have checked the teacher in person against these records and the captured biometrics.</label>
<label>Note (optional)<input name="note"></label><button class="btn primary">Verify teacher</button></form></section>
<?php else: ?><section class="card narrow"><h2>Revoke verification</h2><form method="post" action="<?=url('biometrics/revoke')?>" class="form" data-confirm="Revoke this teacher's verification?"><?=Csrf::field()?><input type="hidden" name="id" value="<?=$t['id']?>"><label>Reason<input name="reason" required></label><button class="btn">Revoke</button></form></section><?php endif; ?>
